// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/accounts/account.proto

package account

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SaveAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveAccountRequest) Reset() {
	*x = SaveAccountRequest{}
	mi := &file_proto_accounts_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveAccountRequest) ProtoMessage() {}

func (x *SaveAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounts_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveAccountRequest.ProtoReflect.Descriptor instead.
func (*SaveAccountRequest) Descriptor() ([]byte, []int) {
	return file_proto_accounts_account_proto_rawDescGZIP(), []int{0}
}

func (x *SaveAccountRequest) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type InitAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MonoToken     string                 `protobuf:"bytes,1,opt,name=mono_token,json=monoToken,proto3" json:"mono_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitAccountRequest) Reset() {
	*x = InitAccountRequest{}
	mi := &file_proto_accounts_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitAccountRequest) ProtoMessage() {}

func (x *InitAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounts_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitAccountRequest.ProtoReflect.Descriptor instead.
func (*InitAccountRequest) Descriptor() ([]byte, []int) {
	return file_proto_accounts_account_proto_rawDescGZIP(), []int{1}
}

func (x *InitAccountRequest) GetMonoToken() string {
	if x != nil {
		return x.MonoToken
	}
	return ""
}

type AccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountResponse) Reset() {
	*x = AccountResponse{}
	mi := &file_proto_accounts_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountResponse) ProtoMessage() {}

func (x *AccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounts_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountResponse.ProtoReflect.Descriptor instead.
func (*AccountResponse) Descriptor() ([]byte, []int) {
	return file_proto_accounts_account_proto_rawDescGZIP(), []int{2}
}

func (x *AccountResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AccountResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Transaction event from webhook
type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"` // "monobank", "privatbank"
	ExternalId    string                 `protobuf:"bytes,2,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	CurrencyCode  int32                  `protobuf:"varint,3,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"` // 980 (UAH), 840 (USD)
	Balance       int64                  `protobuf:"varint,4,opt,name=balance,proto3" json:"balance,omitempty"`                               // in kopiykas/cents
	L4D           string                 `protobuf:"bytes,5,opt,name=l4d,proto3" json:"l4d,omitempty"`                                        // last 4 card's digits
	Name          string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_proto_accounts_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounts_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_proto_accounts_account_proto_rawDescGZIP(), []int{3}
}

func (x *Account) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Account) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *Account) GetCurrencyCode() int32 {
	if x != nil {
		return x.CurrencyCode
	}
	return 0
}

func (x *Account) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *Account) GetL4D() string {
	if x != nil {
		return x.L4D
	}
	return ""
}

func (x *Account) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Jar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExternalId    string                 `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CurrencyCode  int32                  `protobuf:"varint,4,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	Balance       int64                  `protobuf:"varint,5,opt,name=balance,proto3" json:"balance,omitempty"`
	Goal          int64                  `protobuf:"varint,6,opt,name=goal,proto3" json:"goal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Jar) Reset() {
	*x = Jar{}
	mi := &file_proto_accounts_account_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Jar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Jar) ProtoMessage() {}

func (x *Jar) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounts_account_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Jar.ProtoReflect.Descriptor instead.
func (*Jar) Descriptor() ([]byte, []int) {
	return file_proto_accounts_account_proto_rawDescGZIP(), []int{4}
}

func (x *Jar) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *Jar) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Jar) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Jar) GetCurrencyCode() int32 {
	if x != nil {
		return x.CurrencyCode
	}
	return 0
}

func (x *Jar) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *Jar) GetGoal() int64 {
	if x != nil {
		return x.Goal
	}
	return 0
}

type Client struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"` // "monobank", "privatbank"
	ExternalId    string                 `protobuf:"bytes,2,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Accounts      []*Account             `protobuf:"bytes,4,rep,name=accounts,proto3" json:"accounts,omitempty"`
	Jars          []*Jar                 `protobuf:"bytes,5,rep,name=jars,proto3" json:"jars,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Client) Reset() {
	*x = Client{}
	mi := &file_proto_accounts_account_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Client) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client) ProtoMessage() {}

func (x *Client) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounts_account_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client.ProtoReflect.Descriptor instead.
func (*Client) Descriptor() ([]byte, []int) {
	return file_proto_accounts_account_proto_rawDescGZIP(), []int{5}
}

func (x *Client) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Client) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *Client) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Client) GetAccounts() []*Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *Client) GetJars() []*Jar {
	if x != nil {
		return x.Jars
	}
	return nil
}

var File_proto_accounts_account_proto protoreflect.FileDescriptor

const file_proto_accounts_account_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/accounts/account.proto\x12\aaccount\"@\n" +
	"\x12SaveAccountRequest\x12*\n" +
	"\aaccount\x18\x01 \x01(\v2\x10.account.AccountR\aaccount\"3\n" +
	"\x12InitAccountRequest\x12\x1d\n" +
	"\n" +
	"mono_token\x18\x01 \x01(\tR\tmonoToken\"A\n" +
	"\x0fAccountResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xa7\x01\n" +
	"\aAccount\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x1f\n" +
	"\vexternal_id\x18\x02 \x01(\tR\n" +
	"externalId\x12#\n" +
	"\rcurrency_code\x18\x03 \x01(\x05R\fcurrencyCode\x12\x18\n" +
	"\abalance\x18\x04 \x01(\x03R\abalance\x12\x10\n" +
	"\x03l4d\x18\x05 \x01(\tR\x03l4d\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\"\xb1\x01\n" +
	"\x03Jar\x12\x1f\n" +
	"\vexternal_id\x18\x01 \x01(\tR\n" +
	"externalId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12#\n" +
	"\rcurrency_code\x18\x04 \x01(\x05R\fcurrencyCode\x12\x18\n" +
	"\abalance\x18\x05 \x01(\x03R\abalance\x12\x12\n" +
	"\x04goal\x18\x06 \x01(\x03R\x04goal\"\xa5\x01\n" +
	"\x06Client\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x1f\n" +
	"\vexternal_id\x18\x02 \x01(\tR\n" +
	"externalId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12,\n" +
	"\baccounts\x18\x04 \x03(\v2\x10.account.AccountR\baccounts\x12 \n" +
	"\x04jars\x18\x05 \x03(\v2\f.account.JarR\x04jars2\x9c\x01\n" +
	"\x0eAccountService\x12D\n" +
	"\vInitAccount\x12\x1b.account.InitAccountRequest\x1a\x18.account.AccountResponse\x12D\n" +
	"\vSaveAccount\x12\x1b.account.SaveAccountRequest\x1a\x18.account.AccountResponseB3Z1github.com/andrew-pavlov-ua/proto/account;accountb\x06proto3"

var (
	file_proto_accounts_account_proto_rawDescOnce sync.Once
	file_proto_accounts_account_proto_rawDescData []byte
)

func file_proto_accounts_account_proto_rawDescGZIP() []byte {
	file_proto_accounts_account_proto_rawDescOnce.Do(func() {
		file_proto_accounts_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_accounts_account_proto_rawDesc), len(file_proto_accounts_account_proto_rawDesc)))
	})
	return file_proto_accounts_account_proto_rawDescData
}

var file_proto_accounts_account_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_accounts_account_proto_goTypes = []any{
	(*SaveAccountRequest)(nil), // 0: account.SaveAccountRequest
	(*InitAccountRequest)(nil), // 1: account.InitAccountRequest
	(*AccountResponse)(nil),    // 2: account.AccountResponse
	(*Account)(nil),            // 3: account.Account
	(*Jar)(nil),                // 4: account.Jar
	(*Client)(nil),             // 5: account.Client
}
var file_proto_accounts_account_proto_depIdxs = []int32{
	3, // 0: account.SaveAccountRequest.account:type_name -> account.Account
	3, // 1: account.Client.accounts:type_name -> account.Account
	4, // 2: account.Client.jars:type_name -> account.Jar
	1, // 3: account.AccountService.InitAccount:input_type -> account.InitAccountRequest
	0, // 4: account.AccountService.SaveAccount:input_type -> account.SaveAccountRequest
	2, // 5: account.AccountService.InitAccount:output_type -> account.AccountResponse
	2, // 6: account.AccountService.SaveAccount:output_type -> account.AccountResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_accounts_account_proto_init() }
func file_proto_accounts_account_proto_init() {
	if File_proto_accounts_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_accounts_account_proto_rawDesc), len(file_proto_accounts_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_accounts_account_proto_goTypes,
		DependencyIndexes: file_proto_accounts_account_proto_depIdxs,
		MessageInfos:      file_proto_accounts_account_proto_msgTypes,
	}.Build()
	File_proto_accounts_account_proto = out.File
	file_proto_accounts_account_proto_goTypes = nil
	file_proto_accounts_account_proto_depIdxs = nil
}
