// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/transactions/transaction.proto

package transaction

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExternalId    string                 `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransactionRequest) Reset() {
	*x = CreateTransactionRequest{}
	mi := &file_proto_transactions_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionRequest) ProtoMessage() {}

func (x *CreateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transactions_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionRequest.ProtoReflect.Descriptor instead.
func (*CreateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_proto_transactions_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTransactionRequest) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

type CreateTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransactionResponse) Reset() {
	*x = CreateTransactionResponse{}
	mi := &file_proto_transactions_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionResponse) ProtoMessage() {}

func (x *CreateTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transactions_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionResponse.ProtoReflect.Descriptor instead.
func (*CreateTransactionResponse) Descriptor() ([]byte, []int) {
	return file_proto_transactions_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTransactionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Transaction event from webhook
type TransactionCreated struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Source          string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"` // "monobank", "privatbank"
	ExternalId      string                 `protobuf:"bytes,2,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	AccountId       string                 `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Amount          int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`                                 // in kopiykas/cents
	CurrencyCode    int32                  `protobuf:"varint,5,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"` // 980 (UAH), 840 (USD)
	Description     string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Mcc             int32                  `protobuf:"varint,7,opt,name=mcc,proto3" json:"mcc,omitempty"`
	TransactionTime *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=transaction_time,json=transactionTime,proto3" json:"transaction_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TransactionCreated) Reset() {
	*x = TransactionCreated{}
	mi := &file_proto_transactions_transaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionCreated) ProtoMessage() {}

func (x *TransactionCreated) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transactions_transaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionCreated.ProtoReflect.Descriptor instead.
func (*TransactionCreated) Descriptor() ([]byte, []int) {
	return file_proto_transactions_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *TransactionCreated) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *TransactionCreated) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *TransactionCreated) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *TransactionCreated) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransactionCreated) GetCurrencyCode() int32 {
	if x != nil {
		return x.CurrencyCode
	}
	return 0
}

func (x *TransactionCreated) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TransactionCreated) GetMcc() int32 {
	if x != nil {
		return x.Mcc
	}
	return 0
}

func (x *TransactionCreated) GetTransactionTime() *timestamppb.Timestamp {
	if x != nil {
		return x.TransactionTime
	}
	return nil
}

var File_proto_transactions_transaction_proto protoreflect.FileDescriptor

const file_proto_transactions_transaction_proto_rawDesc = "" +
	"\n" +
	"$proto/transactions/transaction.proto\x12\vtransaction\x1a\x1fgoogle/protobuf/timestamp.proto\";\n" +
	"\x18CreateTransactionRequest\x12\x1f\n" +
	"\vexternal_id\x18\x01 \x01(\tR\n" +
	"externalId\"+\n" +
	"\x19CreateTransactionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xa4\x02\n" +
	"\x12TransactionCreated\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x1f\n" +
	"\vexternal_id\x18\x02 \x01(\tR\n" +
	"externalId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\tR\taccountId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12#\n" +
	"\rcurrency_code\x18\x05 \x01(\x05R\fcurrencyCode\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x10\n" +
	"\x03mcc\x18\a \x01(\x05R\x03mcc\x12E\n" +
	"\x10transaction_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x0ftransactionTime2x\n" +
	"\x12TransactionService\x12b\n" +
	"\x11CreateTransaction\x12%.transaction.CreateTransactionRequest\x1a&.transaction.CreateTransactionResponseB;Z9github.com/andrew-pavlov-ua/proto/transaction;transactionb\x06proto3"

var (
	file_proto_transactions_transaction_proto_rawDescOnce sync.Once
	file_proto_transactions_transaction_proto_rawDescData []byte
)

func file_proto_transactions_transaction_proto_rawDescGZIP() []byte {
	file_proto_transactions_transaction_proto_rawDescOnce.Do(func() {
		file_proto_transactions_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_transactions_transaction_proto_rawDesc), len(file_proto_transactions_transaction_proto_rawDesc)))
	})
	return file_proto_transactions_transaction_proto_rawDescData
}

var file_proto_transactions_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_transactions_transaction_proto_goTypes = []any{
	(*CreateTransactionRequest)(nil),  // 0: transaction.CreateTransactionRequest
	(*CreateTransactionResponse)(nil), // 1: transaction.CreateTransactionResponse
	(*TransactionCreated)(nil),        // 2: transaction.TransactionCreated
	(*timestamppb.Timestamp)(nil),     // 3: google.protobuf.Timestamp
}
var file_proto_transactions_transaction_proto_depIdxs = []int32{
	3, // 0: transaction.TransactionCreated.transaction_time:type_name -> google.protobuf.Timestamp
	0, // 1: transaction.TransactionService.CreateTransaction:input_type -> transaction.CreateTransactionRequest
	1, // 2: transaction.TransactionService.CreateTransaction:output_type -> transaction.CreateTransactionResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_transactions_transaction_proto_init() }
func file_proto_transactions_transaction_proto_init() {
	if File_proto_transactions_transaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_transactions_transaction_proto_rawDesc), len(file_proto_transactions_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_transactions_transaction_proto_goTypes,
		DependencyIndexes: file_proto_transactions_transaction_proto_depIdxs,
		MessageInfos:      file_proto_transactions_transaction_proto_msgTypes,
	}.Build()
	File_proto_transactions_transaction_proto = out.File
	file_proto_transactions_transaction_proto_goTypes = nil
	file_proto_transactions_transaction_proto_depIdxs = nil
}
