// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/transactions/transaction.proto

package transaction

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SaveTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExternalId    string                 `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveTransactionRequest) Reset() {
	*x = SaveTransactionRequest{}
	mi := &file_proto_transactions_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveTransactionRequest) ProtoMessage() {}

func (x *SaveTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transactions_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveTransactionRequest.ProtoReflect.Descriptor instead.
func (*SaveTransactionRequest) Descriptor() ([]byte, []int) {
	return file_proto_transactions_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *SaveTransactionRequest) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

type SaveTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveTransactionResponse) Reset() {
	*x = SaveTransactionResponse{}
	mi := &file_proto_transactions_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveTransactionResponse) ProtoMessage() {}

func (x *SaveTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transactions_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveTransactionResponse.ProtoReflect.Descriptor instead.
func (*SaveTransactionResponse) Descriptor() ([]byte, []int) {
	return file_proto_transactions_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *SaveTransactionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SaveTransactionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Transaction event from webhook
type Transaction struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Source          string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"` // "monobank", "privatbank"
	ExternalId      string                 `protobuf:"bytes,2,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	AccountId       string                 `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Amount          int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`                                 // in kopiykas/cents
	CurrencyCode    int32                  `protobuf:"varint,5,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"` // 980 (UAH), 840 (USD)
	Description     string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Mcc             int32                  `protobuf:"varint,7,opt,name=mcc,proto3" json:"mcc,omitempty"`
	TransactionTime *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=transaction_time,json=transactionTime,proto3" json:"transaction_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_proto_transactions_transaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transactions_transaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_proto_transactions_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *Transaction) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Transaction) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *Transaction) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Transaction) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transaction) GetCurrencyCode() int32 {
	if x != nil {
		return x.CurrencyCode
	}
	return 0
}

func (x *Transaction) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Transaction) GetMcc() int32 {
	if x != nil {
		return x.Mcc
	}
	return 0
}

func (x *Transaction) GetTransactionTime() *timestamppb.Timestamp {
	if x != nil {
		return x.TransactionTime
	}
	return nil
}

var File_proto_transactions_transaction_proto protoreflect.FileDescriptor

const file_proto_transactions_transaction_proto_rawDesc = "" +
	"\n" +
	"$proto/transactions/transaction.proto\x12\vtransaction\x1a\x1fgoogle/protobuf/timestamp.proto\"9\n" +
	"\x16SaveTransactionRequest\x12\x1f\n" +
	"\vexternal_id\x18\x01 \x01(\tR\n" +
	"externalId\"I\n" +
	"\x17SaveTransactionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x9d\x02\n" +
	"\vTransaction\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x1f\n" +
	"\vexternal_id\x18\x02 \x01(\tR\n" +
	"externalId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\tR\taccountId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12#\n" +
	"\rcurrency_code\x18\x05 \x01(\x05R\fcurrencyCode\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x10\n" +
	"\x03mcc\x18\a \x01(\x05R\x03mcc\x12E\n" +
	"\x10transaction_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x0ftransactionTime2r\n" +
	"\x12TransactionService\x12\\\n" +
	"\x0fSaveTransaction\x12#.transaction.SaveTransactionRequest\x1a$.transaction.SaveTransactionResponseB;Z9github.com/andrew-pavlov-ua/proto/transaction;transactionb\x06proto3"

var (
	file_proto_transactions_transaction_proto_rawDescOnce sync.Once
	file_proto_transactions_transaction_proto_rawDescData []byte
)

func file_proto_transactions_transaction_proto_rawDescGZIP() []byte {
	file_proto_transactions_transaction_proto_rawDescOnce.Do(func() {
		file_proto_transactions_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_transactions_transaction_proto_rawDesc), len(file_proto_transactions_transaction_proto_rawDesc)))
	})
	return file_proto_transactions_transaction_proto_rawDescData
}

var file_proto_transactions_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_transactions_transaction_proto_goTypes = []any{
	(*SaveTransactionRequest)(nil),  // 0: transaction.SaveTransactionRequest
	(*SaveTransactionResponse)(nil), // 1: transaction.SaveTransactionResponse
	(*Transaction)(nil),             // 2: transaction.Transaction
	(*timestamppb.Timestamp)(nil),   // 3: google.protobuf.Timestamp
}
var file_proto_transactions_transaction_proto_depIdxs = []int32{
	3, // 0: transaction.Transaction.transaction_time:type_name -> google.protobuf.Timestamp
	0, // 1: transaction.TransactionService.SaveTransaction:input_type -> transaction.SaveTransactionRequest
	1, // 2: transaction.TransactionService.SaveTransaction:output_type -> transaction.SaveTransactionResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_transactions_transaction_proto_init() }
func file_proto_transactions_transaction_proto_init() {
	if File_proto_transactions_transaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_transactions_transaction_proto_rawDesc), len(file_proto_transactions_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_transactions_transaction_proto_goTypes,
		DependencyIndexes: file_proto_transactions_transaction_proto_depIdxs,
		MessageInfos:      file_proto_transactions_transaction_proto_msgTypes,
	}.Build()
	File_proto_transactions_transaction_proto = out.File
	file_proto_transactions_transaction_proto_goTypes = nil
	file_proto_transactions_transaction_proto_depIdxs = nil
}
